name: Docker Image Build and Deploy

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:


permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: 
          fetch-depth: 0

      - name: Login to Docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./sample-ci-cd/Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/simple-website:v1

      - name: Notify Slack - Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \":white_check_mark: *Build Succeeded!*\n
            *Job ID:* ${{ github.run_id }}\n
            *Repository:* ${{ github.repository }}\n
            *Branch:* ${{ github.ref_name }}\n
            *Commit:* ${{ github.sha }}\n
            *Workflow:* ${{ github.workflow }}\n
            *Actor:* ${{ github.actor }}
            \"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \":x: *Build Failed!*\n
            *Job ID:* ${{ github.run_id }}\n
            *Repository:* ${{ github.repository }}\n
            *Branch:* ${{ github.ref_name }}\n
            *Commit:* ${{ github.sha }}\n
            *Workflow:* ${{ github.workflow }}\n
            *Actor:* ${{ github.actor }}
            \"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

  deploy:
    runs-on: ubuntu-latest
    needs: build   # deploy runs only after build succeeds
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Pages
        uses: actions/configure-pages@v5

      - name: Upload site
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./sample-ci-cd/html/   # <-- your HTML folder path

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4

      - name: Notify Slack - Success
        if: success()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \":white_check_mark: *website deployed with new version*\n
            *Job ID:* ${{ github.run_id }}\n
            *Repository:* ${{ github.repository }}\n
            *Branch:* ${{ github.ref_name }}\n
            *Commit:* ${{ github.sha }}\n
            *Workflow:* ${{ github.workflow }}\n
            *Actor:* ${{ github.actor }}
            \"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}

      - name: Notify Slack - Failure
        if: failure()
        run: |
          curl -X POST -H 'Content-type: application/json' \
          --data "{
            \"text\": \":x: *New version of webiste failed to update*\n
            *Job ID:* ${{ github.run_id }}\n
            *Repository:* ${{ github.repository }}\n
            *Branch:* ${{ github.ref_name }}\n
            *Commit:* ${{ github.sha }}\n
            *Workflow:* ${{ github.workflow }}\n
            *Actor:* ${{ github.actor }}
            \"}" \
          ${{ secrets.SLACK_WEBHOOK_URL }}
